### ISSUE TITLE
Please adding Hirukowashi

### ISSUE THREAD

**Issue by Binh1412** [masagrator/HigurashiENX-texts#24]
Console Hirukowashi (or Alt. Hirukowashi) now have an English translation by 07th-Mod. Please adding it in. Link for Console Hirukowashi translation: https://github.com/07th-mod/higurashi-rei

**Comment by Binh1412** [comment]
Also, please replace Batsukoishi's MachineTL

**Comment by masagrator** [comment]
It's a beta release. I'm waiting for full release

**Comment by masagrator** [comment]
Welp, I have forgot to add this info too:
I'm waiting half a year after Rei release on Steam to release translation.
So I won't accept any Pull Requests related to Rei chapters before that.
