### ISSUE TITLE
Untranslated line

### ISSUE THREAD

**Issue by SphericalSector** [masagrator/HigurashiENX-texts#3]
Not sure if you were already aware but tip 006 contains an untranslated line:

https://github.com/masagrator/HigurashiENX-texts/blob/master/tips_006.json#L91

**Comment by masagrator** [comment]
Hmm, I missed it it seems.
This is one of tips that needs to be retranslated and this line wasn't available in original tip, so I have left it to fill with machine translation and forgot. Thanks. I will reply again when line will be updated.

**Comment by masagrator** [comment]
Line is updated.
https://github.com/masagrator/HigurashiENX-texts/blob/master/tips_006.json
